# Generated by Django 3.1.3 on 2021-02-04 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='user',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
