# Generated by Django 3.1.3 on 2020-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
