# Generated by Django 3.1.3 on 2021-02-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20210204_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
