# Generated by Django 3.1.3 on 2020-12-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
