# Generated by Django 3.1.3 on 2020-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_customer_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=50, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentification.user',),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentification.user',),
        ),
    ]
