# Generated by Django 3.1.3 on 2020-12-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20201203_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='state',
            new_name='region',
        ),
    ]
