# Generated by Django 3.1.3 on 2021-03-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210318_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='premium',
            new_name='in_store',
        ),
    ]
