# Generated by Django 3.1.3 on 2021-03-22 16:16

import backend.settings.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210319_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CampaignStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='image',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.GiftCardStorage(), upload_to=''),
        ),
    ]
