# Generated by Django 3.1.3 on 2021-03-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Metadata', 'verbose_name_plural': 'Metadata'},
        ),
    ]
