# Generated by Django 3.1.3 on 2021-03-18 12:43

import backend.settings.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('main_store_banner_1', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('main_store_banner_2', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('main_store_banner_3', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Page',
                'verbose_name_plural': 'Store Page',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('partners_page_title', models.CharField(max_length=50)),
                ('partners_page_img', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('partners_page_banner', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('partners_page_paragraph', models.TextField(max_length=500)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partners Page',
                'verbose_name_plural': 'Partners Page',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='NGOPage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('main_ngo_banner_1', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('main_ngo_banner_2', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('main_ngo_banner_3', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NGO Page',
                'verbose_name_plural': 'NGO Page',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('home_page_carousel_img_1', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('home_page_carousel_img_2', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('home_page_carousel_img_3', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('home_page_giftcards_img', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('home_page_happioffers_img', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('home_page_campaigns_img', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('footer_subscription_details', models.CharField(max_length=50)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('about_page_title', models.CharField(max_length=50)),
                ('about_page_title_img', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('about_page_paragraph_top', models.TextField(max_length=250)),
                ('about_page_paragraph_bottom', models.TextField(max_length=250)),
                ('about_page_process_main_title', models.CharField(max_length=50)),
                ('about_page_process_title_1', models.CharField(max_length=50)),
                ('about_page_process_paragraph_1', models.TextField(max_length=250)),
                ('about_page_process_title_2', models.CharField(max_length=50)),
                ('about_page_process_paragraph_2', models.TextField(max_length=250)),
                ('about_page_process_title_3', models.CharField(max_length=50)),
                ('about_page_process_paragraph_3', models.TextField(max_length=250)),
                ('contact_title', models.CharField(max_length=50)),
                ('contact_address', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
                'ordering': ('-published',),
            },
        ),
    ]
