# Generated by Django 3.1.3 on 2021-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='linkedin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
