# Generated by Django 3.1.3 on 2021-03-19 14:59

import backend.settings.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_auto_20210319_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(storage=backend.settings.storage_backends.CustomStorage(), upload_to='')),
                ('link', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.RemoveField(
            model_name='footer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube',
        ),
        migrations.AddField(
            model_name='footer',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='customizations.SocialMedia'),
        ),
    ]
