# Generated by Django 3.1.3 on 2021-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0003_auto_20210319_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
