# Generated by Django 3.1.3 on 2021-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0006_auto_20210319_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200),
            preserve_default=False,
        ),
    ]
