# Generated by Django 3.1.3 on 2021-03-22 15:24

import backend.settings.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0007_auto_20210319_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_page_title_img',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
    ]
