# Generated by Django 3.1.3 on 2021-03-22 16:16

import backend.settings.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0008_auto_20210322_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_page_campaigns_img',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_page_carousel_img_1',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_page_carousel_img_2',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_page_carousel_img_3',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_page_giftcards_img',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_page_happioffers_img',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='ngopage',
            name='main_ngo_banner_1',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='ngopage',
            name='main_ngo_banner_2',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='ngopage',
            name='main_ngo_banner_3',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='partnerspage',
            name='partners_page_banner',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='partnerspage',
            name='partners_page_img',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='storepage',
            name='main_store_banner_1',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='storepage',
            name='main_store_banner_2',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='storepage',
            name='main_store_banner_3',
            field=models.FileField(blank=True, null=True, storage=backend.settings.storage_backends.CustomStorage(), upload_to=''),
        ),
    ]
