from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path(
        "list/basket-campaigns/",
        views.OrderCampaignListView.as_view(),
        name="basket-campaigns-list",
    ),
    path(
        "list/basket-giftcards/",
        views.OrderGiftCardListView.as_view(),
        name="basket-giftcards-list",
    ),
    path(
        "list/orders/",
        views.OrderListView.as_view(),
        name="list-orders",
    ),
    path(
        "create/campaign-to-basket/",
        views.OrderCampaignCreateView.as_view(),
        name="create-campaign-to-basket",
    ),
    path(
        "create/giftcard-to-basket/",
        views.OrderGiftCardCreateView.as_view(),
        name="create-giftcard-to-basket",
    ),
    path(
        "create/order/",
        views.OrderCreateView.as_view(),
        name="create-order",
    ),
    path(
        "create/happicard/",
        views.HappicardCreateView.as_view(),
        name="create-happicard",
    ),
    path(
        "campaign-to-basket/<int:pk>",
        views.OrderCampaignDetailView.as_view(),
        name="campaign-to-basket-detail",
    ),
    path(
        "giftcard-to-basket/<int:pk>",
        views.OrderGiftCardDetailView.as_view(),
        name="giftcard-to-basket-detail",
    ),
    path(
        "order/<int:pk>",
        views.OrderDetailView.as_view(),
        name="order-detail",
    ),
    path(
        "happicard/<int:pk>/",
        views.HappicardDetailView.as_view(),
        name="happicard-detail",
    ),
    path(
        "checkout/",
        views.KlarnaCheckoutView.as_view(),
        name="checkout",
    ),
    path(
        "confirm/checkout/",
        views.KlarnaCheckoutConfirmView.as_view(),
        name="confirm-checkout",
    ),
]