# Generated by Django 3.1.3 on 2021-03-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
