# Generated by Django 3.1.3 on 2021-02-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='business_address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='city',
            new_name='company_category',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='region',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='website',
            new_name='company_role',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='zipcode',
            new_name='corporate_form',
        ),
        migrations.AddField(
            model_name='vendor',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
