# Generated by Django 3.1.3 on 2021-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210214_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Happicard-<function uuid4 at 0x7f8afbf9b040>', max_length=50, verbose_name='Password'),
        ),
    ]
