# Generated by Django 3.1.3 on 2020-12-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201208_1403'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='giftcard',
        ),
        migrations.CreateModel(
            name='OrderGiftCard',
            fields=[
                ('orderproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderproduct')),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.giftcard')),
            ],
            bases=('orders.orderproduct',),
        ),
        migrations.CreateModel(
            name='OrderCampaign',
            fields=[
                ('orderproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderproduct')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.campaign')),
            ],
            bases=('orders.orderproduct',),
        ),
    ]
