# Generated by Django 3.1.3 on 2021-01-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercampaign',
            options={'verbose_name': 'Ordered Campaign', 'verbose_name_plural': 'Ordered Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='ordergiftcard',
            options={'verbose_name': 'Ordered Gift Card', 'verbose_name_plural': 'Ordered Gift Cards'},
        ),
    ]
