# Generated by Django 3.1.3 on 2021-03-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='happicard_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
