# Generated by Django 3.1.3 on 2020-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201208_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='campaigns',
            field=models.ManyToManyField(to='orders.OrderCampaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='giftcards',
            field=models.ManyToManyField(to='orders.OrderGiftCard'),
        ),
    ]
