# Generated by Django 3.1.3 on 2021-01-15 11:15

import backend.settings.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20210111_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happicard',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient_myself', models.BooleanField(default=True)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('recipient_email_choice', models.BooleanField(default=False)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_sms_choice', models.BooleanField(default=False)),
                ('recipient_sms', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_message', models.TextField()),
                ('personal_image', models.FileField(storage=backend.settings.storage_backends.HappicardImageStorage(), upload_to='')),
                ('personal_video', models.FileField(storage=backend.settings.storage_backends.HappicardVideoStorage(), upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='happicard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.happicard'),
        ),
    ]
