# Generated by Django 3.1.3 on 2020-12-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201208_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='orders.OrderCampaign'),
        ),
        migrations.AlterField(
            model_name='order',
            name='giftcards',
            field=models.ManyToManyField(blank=True, to='orders.OrderGiftCard'),
        ),
    ]
