# Generated by Django 3.1.3 on 2021-01-15 13:06

import backend.settings.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210115_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercampaign',
            options={'verbose_name': 'Campaign in Basket', 'verbose_name_plural': 'Campaigns in Basket'},
        ),
        migrations.AlterModelOptions(
            name='ordergiftcard',
            options={'verbose_name': 'Gift Card in Basket', 'verbose_name_plural': 'Gift Cards in Basket'},
        ),
        migrations.RenameField(
            model_name='happicard',
            old_name='recipient_sms',
            new_name='recipient_number',
        ),
        migrations.AlterField(
            model_name='happicard',
            name='personal_image',
            field=models.FileField(null=True, storage=backend.settings.storage_backends.HappicardImageStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='happicard',
            name='personal_video',
            field=models.FileField(null=True, storage=backend.settings.storage_backends.HappicardVideoStorage(), upload_to=''),
        ),
    ]
