# Generated by Django 3.1.3 on 2021-01-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210115_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='happicard',
            name='order_confirm_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
