# Generated by Django 3.1.3 on 2021-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210126_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='happicard',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
