# Generated by Django 3.1.3 on 2020-12-27 18:26

import backend.settings.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('tax_amount', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('image', models.FileField(storage=backend.settings.storage_backends.CampaignStorage(), upload_to='')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('image', models.FileField(storage=backend.settings.storage_backends.GiftCardStorage(), upload_to='')),
                ('has_offer', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0)),
            ],
            bases=('products.product',),
        ),
    ]
