# Generated by Django 3.1.3 on 2021-01-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='giftcard',
            options={'verbose_name': 'Gift Card', 'verbose_name_plural': 'Gift Cards'},
        ),
    ]
