# Generated by Django 3.1.3 on 2020-12-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201208_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
