# Generated by Django 3.1.3 on 2021-01-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210113_1355'),
        ('products', '0003_auto_20210113_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='store',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='store_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.store', to_field='store_category'),
        ),
    ]
