# Generated by Django 3.1.3 on 2021-01-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210113_1412'),
        ('products', '0005_auto_20210113_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='ngo',
        ),
        migrations.AddField(
            model_name='campaign',
            name='ngo_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ngo', to_field='ngo_category'),
        ),
    ]
