# Generated by Django 3.1.3 on 2021-01-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210113_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='ngo_category',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='store_category',
        ),
        migrations.AddField(
            model_name='product',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
