# Generated by Django 3.1.3 on 2021-01-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210113_1422'),
        ('products', '0008_giftcard_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='store_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.store', to_field='store_category'),
        ),
    ]
