# Generated by Django 3.1.3 on 2021-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210118_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='redeem_website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
