# Generated by Django 3.1.3 on 2021-01-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_redeem_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rebate_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
