# Generated by Django 3.1.3 on 2021-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_rebate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rebate_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
