# Generated by Django 3.1.3 on 2020-11-23 14:02

import backend.api.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='brand_category',
            field=models.CharField(blank=True, choices=[('E', 'Electronics'), ('F', 'Fashion & Accessories'), ('D', 'Digital Entertainment'), ('H', 'Home & Garden')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default.jpg', upload_to=backend.api.profiles.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_category',
            field=models.CharField(blank=True, choices=[('N', 'NGO'), ('S', 'Store')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='published'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
