# Generated by Django 3.1.3 on 2021-02-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='items.Campaign'),
        ),
        migrations.AddField(
            model_name='store',
            name='giftcards',
            field=models.ManyToManyField(blank=True, to='items.GiftCard'),
        ),
    ]
