# Generated by Django 3.1.3 on 2021-01-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210111_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Fashion & Accessories', 'Fashion & Accessories'), ('Digital Entertainment', 'Digital Entertainment'), ('Home & Garden', 'Home & Garden')], max_length=50, null=True, unique=True, verbose_name='Store Category'),
        ),
    ]
