# Generated by Django 3.1.3 on 2021-01-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210113_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='ngo_category',
            field=models.CharField(blank=True, choices=[('Non-Profit Organization', 'Non-Profit Organization'), ('Youth', 'Youth'), ('Educational', 'Educational'), ('Literary', 'Literary')], max_length=50, null=True, unique=True, verbose_name='NGO Category'),
        ),
    ]
